project:
  type: book
  output-dir: docs

book:
  title: "rOpenSci Champions Program Internal Playbook [DRAFT]"
  author: "Yanina Bellini Saibene, Camille Santistevan, Lou Woodley, Maya Sanghvi, Maëlle Salmon"
  date: "2024-01-08"
  chapters:
    - index.qmd
    - introduction.qmd
    - section-one-program-overview.qmd
    - section-two-recruitment-and-selection-of-champions-and-mentors.qmd
    - section-three-onboarding-of-champions-and-mentors.qmd
    - section-four-training-and-support-for-champions.qmd
    - section-five-communications.qmd
    - section-six-offboarding.qmd
