project:
  type: book
  output-dir: docs

book:
  title: "rOpenSci Champions Program Internal Playbook [DRAFT]"
  author: "Yanina Bellini Saibene"
  date: "2026-09-25"
  chapters:
    - index.qmd
    - introduction.qmd
    - program-overview.qmd
    - recruitment-and-selection.qmd
    - onboarding.qmd
    - training-and-support.qmd
    - communications.qmd
    - offboarding.qmd
    - evaluation-and-assessment.qmd

format:
  html:
    number-depth: 3
