# Communications

The communication of the program includes two aspects: the _internal communication_, with its participants, and the _external communication_, to shared and inform the community in general. 

The Champions Program have a communication strategy that contemplates the different stages of the program:  

* *Recruiting champions and mentors:* external communication takes the most time and has the most activities in this phase. The @sec-comm-plan-recruitment details the communication plan for this phase. Internal communication is mostly with rOpenSci staff about the implementation of the plan.

* *Selection and onboarding:* at this stage most of the communications are internal with the people involved in the review and selection processes. Here we also inform the results to all the people who applied to the program. The external plan focus on let our community know about the general numbers of the applications, and the mentors and champions selected. 

* *Training:* internal communication is key for the success of this phase, organizing the training session, sharing the resources, following the progress and providing support for champions and mentors. The external communication focus on sharing the training open materials and provide updates to the community about what champions are doing. 

* *Project development and outreach activity:* both aspect are important in this phase. internal communications are to organize cohort meetings, support mentors and champions in their meetings and organize champion events.  External communications are to support champions in publicizing their outreach activities and programm progress.   

* *Offboarding and evaluation:* internal communication is key for the success of this phase to organize the anonymous surveys, individual interviews and focus groups for evaluation. The external communication contemplates to write funder reports and summarizing activities and results for the wider community. 


## External communication

There will be a series of blog posts introducing participants, thanking mentors and trainers, discussing the champion program, and documenting what has been learned so far. Blog post would be shared on other media and can be complement with other kinds of communication artifacts.

The blog posts will be a way of codifying everything the champions are learning, and shows them how far they’ve come. It also offers visibility for all involved in the program, including mentors, champions, and trainers, as well as being useful content to share with funders.

Blog posts are also a nice way to thank and acknowledge the contributions of all the folks involved in the champion program.

The external communication use the following media:

* Champions Web Page.
* rOpenSci Blog Post and Newsletter.
* rOpenSci Social Media.
* rOpenSci Community Calls and Co-working sessions.
* Events with other communities.

::: callout-note
During the two years pilot of the program the social media landscape changed substantially due to the change of ownership of X (former Twitter), which implied a change in the way the program was communicated externally. 
:::

As the @sec-comm-plan-recruitment details the communication plan for the _Recruiting champions and mentors_ phase and how we use the differents media, in the following sessions we describe the communication plan and tools for the rest of the phase of the Champions Program.

### Selection and onboarding

* The first step is to **inform the results of the call**, e.g. the number of applications received, the type of project and from where are the applicants.  

For example, this blog post for the first cohort [rOpenSci Champions Program Kick off](https://ropensci.org/blog/2023/02/21/champions-program-kick-off/) (also in [Spanish](https://ropensci.org/es/blog/2023/02/21/champions-program-kick-off-es/)) presents general stats for the applications and introduce the selected participants.  Also share information about the kick-off meetings and training activities. 

This Mastodon post is about the second cohort:

<iframe src="https://hachyderm.io/@rOpenSci/111018136730918068/embed" width="500" height ="700" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-forms"></iframe>

All blog post are shared on the monthly newsletter and in some Slack related with the program.

* The second step is to **update the Champions Program** webpage:

- Create an author profile for each Champions and Mentor selected: this will allow Champions and Mentors to be author on different type of contributions to rOpenSci.

- List them on the Champions Program's web page: this means upload their profile picture and add their affiliation and path for communication.

- Remove from the main page all of the information about the open call.

- Add the information about the program's timeline on the main webpage. 

* The third step is **draft the blog post** introducing champions and mentors to the community. We tried two ideas to communicate about the selected champions and mentors. 

#### Blog post series on champions and mentors

For the first cohort we write a series of ten blog posts, two each week. Each one will focus on a
project team, which will typically consist of a champion and mentor, and the content will include who they are (biographical information) and what the project is about.

The Champions and Mentors have already filled out an AirTable form with headshots and other biographical information that will be useful in these blog posts. The Community Manager will create the skeleton with the info she already has, and the champions / mentors can edit it.

This are the published blog post in the series:

  * [rOpenSci Champions Program Teams: Meet Ghozayel Elotteebi and Zebulun Arendsee](https://ropensci.org/blog/2023/06/23/ropensci-champions-program-teams-meet-ghozayel-elotteebi-and-zebulun-arendsee/)

  * [rOpenSci Champions Program Teams: Meet Alican Cagri Gokcek and Elio Campitelli](https://ropensci.org/blog/2023/06/19/ropensci-champions-program-teams-meet-alican-cagri-gokcek-and-elio-campitelli/)

  * [rOpenSci Champions Program Teams: Meet Cheryl Isabella Lim and Mauro Lepore](https://ropensci.org/blog/2023/06/12/ropensci-champions-program-teams-meet-cheryl-isabella-lim-and-mauro-lepore/)

  * [rOpenSci Champions Program Teams: Meet César and Marc](https://ropensci.org/blog/2023/05/18/ropensci-champions-program-teams-meet-césar-and-marc/)

  * [rOpenSci Champions Program Teams: Meet Victor Ordu and Laura DeCicco](https://ropensci.org/blog/2023/05/11/intro-champion-program-team-victor-laura/)

  * [rOpenSci Champions Program Teams: Meet Haydee Svab and Beatriz Milz](https://ropensci.org/blog/2023/05/09/ropensci-champions-program-teams-meet-haydee-svab-and-beatriz-milz/)

  * [rOpenSci Champions Program Teams: Meet Carolina Pradier and Athanasia Monika Mowinckel](https://ropensci.org/blog/2023/05/05/ropensci-champions-program-teams-meet-carolina-pradier-and-athanasia-monika-mowinckel/)

  * [rOpenSci Champions Program Teams: Meet Bilikisu Wunmi Olatunji and Christina Maimone](https://ropensci.org/blog/2023/04/25/ropensci-champions-program-teams-meet-bilikisu-wunmi-olatunji-and-christina-maimone/)

  * [rOpenSci Champions Program Teams: Meet Marcos Prunello and Lukas Wallrich](https://ropensci.org/blog/2023/04/18/ropensci-champions-program-teams-meet-marcos-prunello-and-lukas-wallrich/)

  * [rOpenSci Champions Program Teams: Meet Pao Corrales and Adam Sparks](https://ropensci.org/blog/2023/04/13/ropensci-champions-program-teams-meet-pao-corrales-and-adam-sparks/)

For the second cohort, we selected Mentors first because they helped with the review and final selection of champions. We decide to do two blog post, the first one introducing mentors and after the Champions selection was finished one blog post introducing champions.

The process was the same we use for the first cohort strategy regarding using the AirTable picture and information.  We provide better instruction on how to write the text, for example, write your bibliography in the first person.  The result was less time to edit the text for the blog post and less time to review the text by mentors and champions before post them. 

These are the two second cohort's introduction blog post:

  * [Introducing rOpenSci Champions - Cohort 2023-2024](https://ropensci.org/blog/2024/02/15/champions-program-champions-2024/)

  * [Introducing rOpenSci Mentors - Cohort 2023-2024](https://ropensci.org/blog/2023/11/29/champions-program-mentors-2023/)


### Training

During champion and mentor training we report at three points:

1) Each meeting is mentioned on social networks, the topic, who the instructors are and the materials are shared.  You can also accompany the social media post with a screenshot of the workshop attendees.

<iframe src="https://mastodon.social/@maelle/111935537671485326/embed" width="400" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-forms"></iframe>

<iframe src="https://fosstodon.org/@yabellini/112014960765671248/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script src="https://fosstodon.org/embed.js" async="async"></script>

2) During the workshops we identify topics and advice that result in blog posts published on our website, or on the instructors' websites.  They are shared in the newsletter and on social media.

* [An Example of the DRY/DAMP Principles for Package Tests](https://ropensci.org/blog/2024/03/18/dry-damp/)

* [Beautiful Code, Because We’re Worth It!](https://ropensci.org/blog/2024/02/22/beautiful-code/)

* [Marketing Ideas For Your Package](https://ropensci.org/blog/2024/03/07/package-marketing/)

3) At the end of the training phase, a blog post is made closing this stage where we share how the training was structured, what topics were taught and the feedback from the attendees.  

* Blog post for the first cohort: [rOpenSci Champions Pilot Year: Training Wrap-Up](https://ropensci.org/blog/2023/08/04/champions-program-training/)

<iframe src="https://hachyderm.io/@rOpenSci/110831490540399654/embed" width="400" height="700" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-forms"></iframe>

This helps to share with the community what is happening in real time, what was learned during the whole process and makes the materials available for the community to benefit from. 

Finally, the training details are include in the final report for our funders. 


### Champions Project and Outreach

There are two goals in the communication about Champions' projects and outreach activity:

1. Share details about the projects with the community.

2. Support champions outreach activity spreading the word and sharing results. 

For example, this is a series of post on social media about each Champion project:

* Package eph: https://hachyderm.io/@rOpenSci/110967418654944210

* Package naijR: https://hachyderm.io/@rOpenSci/110972893704549099

* Package Agroclimatico: https://hachyderm.io/@rOpenSci/111030133176328601

* Cagri's project: https://hachyderm.io/@rOpenSci/111063737136002081

* Package Lextale: https://hachyderm.io/@rOpenSci/111057655654084693

* Package chartkickR: https://hachyderm.io/@rOpenSci/111052400785146165

* Package karel: https://hachyderm.io/@rOpenSci/111046359173545680

* Package rgeeextra: https://hachyderm.io/@rOpenSci/110985914847076073

* Package odbr: https://hachyderm.io/@rOpenSci/110978882839376351

These are two blog post, the first one is a Champions' blog post and the second one a summary of all Champions' activities:

* [rOpensci Champions Program: My Experience](https://ropensci.org/blog/2023/12/19/champions-program-2023-experience/) by Bilikisu Wunmi Olatunji.

* [Participación Latinoamérica en el Programa de Campeonas y Campeones de rOpenSci](https://ropensci.org/es/blog/2024/01/09/champions-program-latinr/)

* Social media post about the Latin American projects blog post

<iframe src="https://hachyderm.io/@rOpenSci/111726609754320957/embed" width="400" height="750" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-forms"></iframe>

To support the outreach activities we publish the event in rOpenSci Events Calendar, announce it on social media and different Slack before the event. After the event we publish the material on rOpenSci website, vimeo and Slack.  We shared these material on social media.

For example for the package eph organize a Community Call in Spanish. These are the communication pieces, also in Spanish:

* [Event post on the rOpenSci Website](https://ropensci.org/events/2023-12-15-eph/): before the event is listed on the webpage with information about what, when, where and how to join.  After the same web page list all the materials like slides and video. 

* [Mastodon post inviting people to the event](https://hachyderm.io/@rOpenSci/111511495875929503)

* [Mastodon thread explaining the improvments on the eph package and inviting to the event](https://hachyderm.io/@rOpenSci/111405919207883849)

* [Mastodon post after published all the materials of the eph event](https://hachyderm.io/@rOpenSci/111693596413446940)


### Offboarding and evaluation

The external communication contemplates to write funder reports and summarizing activities and results for the wider community. 

* [rOpenSci Champions Pilot Year: Projects Wrap-Up](https://ropensci.org/blog/2024/03/20/champions-program-projects-cohort1/)


### Blog post series on documenting the program

During all the pilot of the Champions Program, we discuss and documents our processes. We also change those base on our participant and community feedback. We write a series of blog post, organize events and delivered a series of talk to document and share what has been learned so far. Here are examples:

* Blog post: [Fostering Equity and Leadership: the rOpenSci Champions Program Selection Process](https://ropensci.org/blog/2024/04/18/champions-program-2024/)

* Talk: [Fostering Diversity and Sustainability in the Open Source Scientific Software Community. The rOpenSci Champions Program](https://ropensci.org/events/opdevroom-2024/)

* Event and blog post: [How do you measure the impact of a champions program?](https://ropensci.org/blog/2023/06/15/ropensci-champions-impact-en/)

* Talk: [A mentoring & training program for Scientific Open Source Champions](https://docs.google.com/presentation/d/1-aneDjY1NsBCN_jfRMVl0aB8fddWbdGlxbGQfdr5fkY/edit#slide=id.ge23cc3131b_0_32)



## Internal communication

Communication with champions and mentors takes place in the following spaces: 

- Slack (more detail in @sec-infrastructure).
- Email.
- Champions Program meetings (training sessions, cohort meetings, etc.)

The Program Manager share important information using always two channels: Slack and emails. Most of the time is the same message for both media.



### What to do when Champions are disengaged from the program

In the first year, the rOpenSci Community Manager noted that three of
the ten champions were slightly off track from the goals of the program.
One champion had a project idea that was out of scope, while two were
not showing up to the training sessions and meetings.

Each situation will be unique, and so it is important to consider the
champion’s specific circumstances and tailor an intervention to the
needs of the situation. However, some general guidelines can be helpful
when champions are off track:

- *Have one-on-one meetings with the champion and / or their mentor.*
  Often, just talking through the problem can be enough to generate
  solutions.

- *Intervene early and check-in often*. Don’t let the problem get out of
  hand – at the first hints of an issue, reach out to the mentor or
  champion and make sure they are feeling supported.

- If a champion can’t participate for whatever reason, offer the
  opportunity to another applicant.

  - Make expectations for the program clear from the start in early
    communication, and disclose that lack of proper engagement may lead
    to removal from the champion program.

In the three specific situations listed above, speaking with the mentors
and champions allowed the Community Manager to co-create solutions that
fit everyone. The out of scope project will have a different status in
the R ecosystem, but will still benefit from the rOpenSci review process
and therefore be fast-tracked to publishing in a journal. Meanwhile, the
disengagement was handled by changing training schedules to be more
accommodating.

### Time Zone Concerns

Given the explicit goal of including a diverse range of people in the
champion program, the issue of time zones has emerged – champions have
nine hour time differences. It is important to organize training
sessions accommodating these time zones, and to take into account that
the United States and the UK have Daylight Savings time in March and
November which disrupt typical time differences.

An important solution is to ask for the applicant’s time zone in the
application form for the champion program to ensure that all those
accepted will have some working-hour overlap in which they are able to
meet.

A helpful resource for planning across time zones is this [*Time Zone
Converter – Time Difference
Calculator*](https://www.timeanddate.com/worldclock/converter.html)
which allows you to compare times in several time zones at once and
determine whether it is during waking hours or not.

### Coffee Chats

The Community Manager should set up coffee chats for the champions. This
is a great way to give them permission to reach out to one another
outside of facilitated chats, and allows them to connect outside of
official meeting times. It will add to the sense of camaraderie and
community if they have personal connections to one another; champions
have already noted and interest in engaging with each other outside of
training sessions.


## Infrastructure for communications and documentation

A useful program called Cartero sends out personalized emails, and the
Community Manager only has to give an email template and list of names.

Another program called Quartificate creates quarto books automatically:
[*rOpenSci Community Contributing
Guide*](https://contributing.ropensci.org/) (Yani has one for mentors
and champions)

- [*Transform Google Doc to Quarto
  book*](https://docs.ropensci.org/quartificate/reference/quartificate.html)

- The Community Manager needs to settle questions around how private or
  public facing quarto books should be, and what personal content it
  should include (e.g., contact info)




