# Training and support for Champions

## Overview

Champions will receive training on (1) how to plan and facilitate engaging and inclusive workshops to support participants’ success (by CSCCE), (2) channels through which new members can engage in and contribute to Open Source projects, and (3) technical skills in software development and review. This series of 60 to 180-minute sessions will be supplemented by ongoing peer connection in a private Slack channel so that Champions expand their own professional support networks while gaining new skills.

After training, Champions will organize peer groups in communities in which they are embedded. They will promote participation in peer review and contribution to rOpenSci open source software, infrastructure, and documentation and gather feedback on where rOpenSci’s current programming might be improved to meet the needs of all who wish to participate. The tenure and responsibilities of each cohort will have clear start and end dates and Champions will receive an honorarium.

## Trainers

While the Community Manager has led and helped organize many of the training sessions, trainers have come from outside of the Champions Program. Having a diversity of trainers helps support the mission of the Champion Program to increase access to the R ecosystem.

| **Trainer Name**       | **Connection to rOpenSci** | **Training Led** |
|------------------------|----------------------------|------------------|
| Camille Santistevan    | CSCCE Staff                | First cohort PACT|
| Maya Sanghvi           | CSCCE Staff                | First cohort PACT|
| Maëlle Salmon          | Staff                      | Package Development |
| Mauro Lepore           | Reviewer/Editor            | Peer-review                 |
| Heather Turner         | R Foundation               | First cohort - How to contribute to base R                  |
| Yanina Bellini Saibene | Staff                      | Mentoring - How to contribute to OSS                 |
| *Paola Corrales*       | Champion                   | Git and GitHub        |
| Noam Ross | Staff | Peer-review |

## Workshops

### Technical Track

-   [**Beautiful Code, Because We’re Worth It!.**](https://stylish-code.netlify.app/#/) Added for the second cohort is a one-hour session to present [good practices on writing code](https://ropensci.org/blog/2024/02/22/beautiful-code/). It is the first session of the technical training.

-   [**Package Development: The Mechanics**](https://rpkgdev-mechanics.netlify.app/)**.** two-hour hands-on session with a live demo on creating R packages hosted by rOpenSci staff Maëlle Salmon and Yanina Bellini Saibene. For the second cohort, we split this training into [three 2-hour sessions](https://rpkgdev-mechanics-2024.netlify.app/) with more content and more time for the hands-on exercises. It is training for beginners to demystify the creation of an R package.

-   [**Package Development: Not Rocket Science**](https://rpkgdev-rocket.netlify.app/)**.** two-hour hands-on workshop for advanced R package development with several tips and tricks on package development hosted by rOpenSci staff Maëlle Salmon and Yanina Bellini Saibene. 

-   [**How rOpenSci Performs Peer Review**](https://github.com/maurolepore/ropensci-review)**.** one-hour workshop to showcase and discuss how rOpenSci communicates, builds, and reviews software with selected examples and resources hosted by rOpenSci community member and mentor Mauro Lepore. We add one more session with case analysis and practices, for the second cohort.

-   [**Developing Software Together**](https://paocorrales.github.io/git-developing-software-together/). 3-hour course on using Git and GitHub to collaboratively develop open-source software with the R language. Hosted by the champion Paola Corrales and rOpenSci staff Yanina Bellini Saibene.

    ::: callout-tip
    Developing Software together was offered to all the non-selected applicants

    One of the goals of this program was to ensure that all participants gained new skills and understanding. We also wanted to support those who applied to the program but were not selected. Therefore we ensured that all groups had access to different training opportunities.
    :::

    ::: callout-note
    [**How to contribute to base R**](https://ropensci.org/events/2023-05-18-how-to-contribute-base-r/) 1-hour workshop with a walk-through of how to contribute to base R. It included how to contribute to a bug, confirm a bug, diagnose a bug, and propose a fix to code/documentation hosted by R Foundation member Heather Turner for the first cohort.
    :::

### Community Track

-   **Making a PACT for engaging virtual meetings and events.** 1.5-hour workshop hosted by CSCCE. Participants explored designing and facilitating engaging and productive virtual meetings and events. Participants discuss the opportunities and challenges of working together online and outline the “Making a PACT” framework for effective meeting design. In addition to examples of the framework in action, attendees can apply it directly to some example scenarios so that participants leave feeling empowered to use the framework in their work. Participants are welcome to review the CSCCE’s free guidebook on Zenodo ahead of the session: [*A guide to using virtual events to facilitation community building: Making a PACT for more engaging virtual meetings and events*](https://zenodo.org/record/4987666#.Y-1Y4nbMK5c)

-   **Path for contributing to rOpenSci.** Added for the second cohort. One 2-hour session to present paths for collaboration and engagement beyond the Champions Program.

-   **Teaching and Learning Tech Together.** This was added for the second cohort. It is a 3-hour session with evidence-based pedagogical concepts to apply in teaching, events, talks, mentoring, documentation, and other spaces where we need to share content and knowledge.

## Training Session Organization

### Schedule

Champions share their availability in a pool and the Community Manager select with the instructor availability the best day of the week and time during the day for maximizing attendance.

Half of the weekly session are schedule and the invitation are sent with a detail of the topic of each workshop with the material we will use in advance. When half of the session were completed the time of the session changes to accommodate better those Champions that can't attend the first option synchronously.

This configuration is a good mix between flexibility in the timing of training and knowing the schedule in advance.

::: callout-note
For the first cohort we made a pool to chose the day and time of each training. We offer two session for each workshop in different timezones and record the training. The feedback was very good on the flexibility aspect but many Champions request to know in advance when the session will happen.
:::

### Workshop Session

There is a check list of task to fo for each training session.

* **One day before the training session**: 

1. [Use the template]() to create the collaborative note taking document. Remember to check with Champions if the tool is accessible for them. 

2. Send and email and post a message on the Slack channel with a reminder of the training.  Include the link to the zoom meeting and the session material.

* **Before the start of the training session**:

3.  One hour before the training session send and email and post a message on the Slack channel tagging to the channel with a reminder of the training.  Include the link to the zoom meeting and the session material.

4. Start the meeting 15 minutes early.

5. When the instructor join, give co-host permission. Check audio, video and screen sharing. Check access to the document and link to the materials. 

* **During the training session**:

6. Remove the waiting room and allow all participants to join.

7. Welcome the attendees and mention we will record the session.  Start the recording. All the material is only shared with the cohort. 

8. Mention the CoC, share the collaborative note taking doc, introduce the instructor and pass the lead of the session to them.

9. Share on the chat the links to the collaborative note taking document.

10. Manage the breakout rooms.

11. Share the anonymous feedback survey (last 5 minutes) for people to fill before they leave.

* **After the training**

12. Check the feedback survey and decide what can be improve for the next session.

13. When the video recording is ready, create the folder for the session in the Google drive for the cohort and upload all the necessary files.  Edit the video if necessary, and summary the content with timestamp.

14. Then send the email and post the message in Slack sharing the following materials:

  - Slides.
  - Video.
  - Video summary with timestamp (this is generated with Zoom tools).    
  - Automatic Subtitles. 
  - Chat.
  - Transcript.
  - Shared notes.
  - Link to Feedback Survey.
  

::: callout-note
Video summary with timestamp, automatic subtitles, transcript and chat are tools to increase the accessibility of the material. 

The summary with timestamps was also a request from Champions of the first cohort to check the material without the need to watch all the video.  
:::

#### Invitation mail template

> “Dear Champions and Mentors. This is the invitation to our next training session on [topic]
> 
[Name of the instructor] will be our speaker. [Name of the instructor] is [short bio].
>
> This training is open to all. It is especially important for Champions who are going to send a package for review or are going to become a reviewer. It is optional for mentors.”

## Post-training programming

### Co-hort meetings

Four cohort meetings were planned, one for each quarter with a duration of 90 minutes. Mentors are invited to participate.

* First Cohort meeting: Project Presentations. Champions give 5 min presentations of their projects (package review or development) and receive feedback.

* Second Cohort meeting: Project Reflections. Champions will be invited to share takeaways from their projects with the cohort.	

*	Third Cohort meeting: Reflections on events.	Champions will be invited to share their ideas for their outreach activity and takeaways from their events with the cohort.	

* Fourth Cohort meeting: Reflections on program. Champions will be invited to share takeaways from the program with the cohort and start to define future roles for Champions.

::: callout-note
The last Cohort Meeting was also a good moment to present the results of each project and to celebrate what all Champions accomplished.  
:::

### Office hours and co-working sessions

After training sessions, the Champions may benefit from office hours and / or co-working sessions to ask questions about what they’ve learned and apply it to their own package development projects.

rOpenSci staff can hots this office and co-working hours.

### Resources and support for Champions’ outreach activities

- List of potential events to participate

- Apply for scholarships to present at conferences.
    
::: callout-note
For the second cohort we shared Posit Conf and useR! scholarship opportunities and request to mentors to support their Champions on the applications.

Several Champions applied and were awarded with the scholarship.  One of them express they get to know about the opportunity because of the Champions Program.
:::

- The Community Manager has been redirecting invitations to talk or teach to the Champions

  - Share in Slack

  - Targeted invites to Champions and mentors - tends to work better that a general message on the private channel of the Champions Program.

  - Champions have been paid to participate in some of these opportunities.

  - Part of the scaffolding is a folder with rOpenSci branding, slides templates, etc. so the Champions can use it in their events.


## Open and Sharing Traninig and Program Materials

For the first cohort the Community Manager shared [*the training materials*](https://github.com/ropensci-training) from each training session online after it’s completed. 

For the second cohort we are updating the content and sharing it openly at the same time we are running the session. We also summarize some of the content on [blog post or tech note](https://ropensci.org/tags/champions-program/) for our webpage.  This way we can share this knowledge with the rest of the R community.

The second year we are also opening the information on how to organize a Champions Program. We already share some insight on blog post and [talks](https://ropensci.org/talks-papers/) during the program pilot. This play book present detailed content and templates on how we run our program.
