# Onboarding of champions and mentors

## Overview

This section describes the onboarding process for both champions and
mentors. Prior to onboarding meetings, a number of scaffolding pieces
are put into place, including a Google Drive, Slack, and templates for
meetings between mentors and champions. 

For the first cohort mentors and champions meet each other during the program kick-off
meeting. For the second cohort the first one-on-one meeting is organized for the mentor. 

For the second cohort we celebrate kick-off meeting for mentors and champions separately. 
Mentors were invited to the champions kick-off meeting.

Mentors attend a training and orientation meeting to
share expectations and tools needed for the program.

## Infrastructure

* **Slack**: we have four private channels for your communication with participants in the program:

  * **#mentors-year**: only mentors of the _year_ cohort in this channel. For example, #mentors-2024 is the channel for the mentor of the second cohort. Mentors can ask questions, share resources, ask for advice from their peers. 

  * **#champions-year**: only champions of the _year_ cohort in this channel. Champions can ask questions about the training or their projects, share resources, ask for advice, etc. 
  
  * **#champions-and-mentors-year**: a channel with all the participants of the _year_ cohort. Training materials and outreach activities are shared in this channels. 

  * **#champions-program**: a channel with all the participants of the program in all the cohort.

  rOpenSci staff members are in all the channels to provide support and share information.

* **Google Drive**: the google drive contain:

  * a folder for each champion with their application and other material the champion will generate as part of their work on the program.
  
  * **training-resource** folder: contain one folder for each training session with all the material (slides, video, documents, etc).
  
* **Templates and monthly charter:** templates for mentoring meetings and monthly charter with task and activity by month.

* **Branding:** rOpenSci branding material for use on outreach activities.

* **Airtable forms and databases**: reporting of mentoring meeting, feedback for meeting and training, champions pledge, information for champions and mentors for blog post.

* **Review process**: a series of spreadsheets with the review task and rubric.

* **Web page**: the Champions Program web page have a section to list all champions and mentor of each cohort.

## Onboarding process

### Mentors

#### Letter of acceptance 

Selected mentors get a email with the notification and a series of steps on how to get started. Here is a template of the message.

> Dear [Name],
>
>Thank you for your application to be a mentor for the rOpenSci Champions Program. We have completed our application review, and I am delighted to be able to invite you to join us for our second cohort starting in [year]!
>
>Here is some information on how to get started!
>
> * We will ask you to review the applications of the potential champions to help us in the final selection. We will send you information on the rubric and the list of applications during the week of [week].
>
> * Please complete these polls for the kick-off meeting by [date]. Our first meeting will most likely fall by the last week of [month, year] or the first week of [month, year]. These links present a pool for each week. Please be sure to put all possible times to help us find time that will include everyone. Be sure to check and select your time zone at the top of the poll before filling your times. [links to the pools]
>
> * Please complete this form with information about you by [date] that we will use for a blog post (full name, degrees, country of origin and country of residency, your current activities, what is your project and what do you expect on the champion program). [link to the form]
>
>* We will invite you to our Slack, please reply to this email with the email account you want to be invited to Slack.
>
>* Please check out our tentative program schedule. [link to the schedulle]
>
>Please note that acceptance is contingent upon your ability to fully participate in the program. If you are unable to commit to participating at this time, please let me know by [date].
>
>Welcome to the rOpenSci Champions Program!
>
>Please get in touch with questions – we really appreciate your interest. This program wouldn’t run without you.
>
>Sincerely,

> [Name] 
> rOpenSci Community Manager

#### Kick-off meeting & Infrastructure Access

The community manager hosts a kick-off meeting to introduce the mentors to each other, provide an overview of the program,
review the tentative training schedule and expectations for the program.

The community manager also shares information about tools and
infrastructure that will be used to communicate and collaborate during
the program, such as Slack, Google Drive, template docs, and shared
calendar.

The kick-off meeting was offered in 3 different time zones. It is important that all mentors can attend this meeting. 

* [Kickoff mentor meeting 2023-2024 Slides](https://docs.google.com/presentation/d/1E9SAS_uYOyz9dm6bDsPB6b3pgtQTHCONbLi1WRB1ClE/)

* [Kickoff mentor and champions meeting 2022-2023](https://docs.google.com/presentation/d/1K4HDAvxk3MkKN2DCr_oYSx1lE73fDI8Ri1Bxo8z83ow/)

At this point mentors are granted access to all the infrastructure, like Slack channels, Google drive, review tools and templates.  

#### Webpage and Blog post

As last step on the onboarding process of mentors, the community manager update the Champions Program webpage with the picture, affiliation and contact information of all the mentors. 

The CM create a draft of the author profile of each mentor and the [blog post introducing them](https://ropensci.org/blog/2023/11/29/champions-program-mentors-2023/).  Mentors are invited to review this information before publication.   

Mentors' information use for create this content was share by mentors using an Airtable form. 

### Champions

#### Letter of acceptance 

#### Step 1: Kick-off meeting / initial mentor/mentee introductions

The community manager hosts a kick-off meeting to introduce the
champions and mentors to each other, provide an overview of the program,
review the tentative training schedule and expectations for the program.
The community manager also shares information about tool and
infrastructure that will be used to communicate and collaborate during
the program, such as Slack, Google Drive, template docs, and shared
calendar.

Kick-off meeting materials:

- [*rOpenSci - Champion Program -
  KickOff*](https://docs.google.com/presentation/d/1K4HDAvxk3MkKN2DCr_oYSx1lE73fDI8Ri1Bxo8z83ow/edit#slide=id.g1db4e36fb1d_1_0)

- [*Notes - Kick-off Meeting Champions
  Program*](https://docs.google.com/document/d/1qH6FyBo-ZJ-KM5FTR-XNauAMPGRbW7csc7I02eRaNYQ/edit)

#### Step 2: Mentor training and orientation meeting

After the initial kickoff, the mentors have a 75 minute meeting with the
rOpenSci Community Manager with the purpose of giving them tools,
skills, and guidance to provide good mentorship to the champions.

The overarching message of the meeting is that the role of a mentor is
to advise and inspire. They can do this by recommending resources,
offering feedback, and connecting their mentees to other people or
programs.

The content of the first meeting can be broken down into a skills and
tools section.

The skills are aimed at:

- Active listening

- Effective questioning

- Giving feedback

Tools include guidance on:

- Setting expectations for meetings

- The GROW Model for exploring and reflecting

  - Goal: Agree on a topic & objective or longer-term goals

  - Reality: self-assessment, specific examples

  - Options: suggestions offered & choices made

  - Way forward: next steps

During the meeting, mentors also have time to reflect on their own
mentorship experiences (as a mentor or mentee), practice the GROW model,
and consider their readiness for being a mentor.

##### Mentor training and orientation materials

- [*rOpenSci Champions Program Mentor Guidelines
  v1.0*](https://docs.google.com/document/d/1oEN_6anF2hlUJcHOqL78kVDK9W1pl4zW3BUtgozI0AE/edit#)

- Slide deck: [*rOpenSci - Champion Program - Mentorship Training and
  Orientation*](https://docs.google.com/presentation/d/1qAv8IfSMRRGbQlwOkyM7QvnYQSEvL-cUFPj72ixNgN4/edit)

- [*Mentor materials and
  resources*](https://drive.google.com/drive/folders/1IAMCn01yh_YeAngkcb1rcvCgnp5OT0t8)

- Web page with instructors notes:
  [*https://ropensci-training.github.io/ropensci-mentors/*](https://ropensci-training.github.io/ropensci-mentors/)

#### Step 3: Champion and mentor 1-on-1 meetings

Mentors are positioned to help champions progress their projects, answer
questions, and provide motivation and support. One way for the pair to
keep up to date with each other is by monthly 1-on-1 meetings, of which
they are expected to have around 11 and can have more. The meetings
should be about 30 minutes, but can be shorter or longer depending on
both people’s needs and availability.

Mentor and champion pairs are expected to decide on meeting times and
platforms with each other and are provided with a
[*list*](https://docs.google.com/document/d/1oEN_6anF2hlUJcHOqL78kVDK9W1pl4zW3BUtgozI0AE/edit#heading=h.ierqx96guq2c)
of potential collaboration platforms including Zoom, Slack, WhatsApp,
Google Docs, and When2Meet. They are also expected to read, implement,
and abide by rOpenSci’s [*Code of
Conduct*](https://ropensci.org/code-of-conduct/) in their meetings and
interactions.

After the mentor orientation, the mentors are given a
[*template*](https://docs.google.com/document/d/1vjmfbjv9ABJ6fkbtQRMFPydJZ3ypKOIpZ-xf7_iBhvo/edit)
for their first meeting with their mentees and asked to set an agenda
with goals, possible areas they can investigate, and expectations for
each other. Mentors are expected to complete a form to confirm with the
community manager that these monthly meetings are taking place.

Subsequent meetings between the two will be structured as a check-in to
ensure that the champion is keeping up with their goals and to answer
any questions they may have. The final meeting will offer an opportunity
for both to celebrate their accomplishments and offer feedback. More
details about the meetings can be found in the [*Mentorship
Meetings*](https://docs.google.com/document/d/1oEN_6anF2hlUJcHOqL78kVDK9W1pl4zW3BUtgozI0AE/edit#heading=h.k5vsm0igh6zd)
section of the Mentor Guidebook.
